# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI - Ubuntu Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: ls build
    # - name: Creating 7z compression files (of build-linux-AppImage)
    #   uses: edgarrc/action-7z@v1.0.4
    #   with:
    #     args: 7z a -t7z -mx=9 build/DanmakuTree-0.0.1.AppImage.7z ./build/DanmakuTree-0.0.1.AppImage
    # - name: Creating 7z compression files (of build-linux-unpacked)
    #   uses: edgarrc/action-7z@v1.0.4
    #   with:
    #     args: 7z a -t7z -mx=9 build/linux-unpacked.7z ./build/linux-unpacked
    - name: Upload build-linux-AppImage artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/DanmakuTree-*.AppImage
    - name: Upload build-linux-unpacked artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/danmaku-tree-*.7z